### ISSUE TITLE
UnsupportedOperationException: empty.max

### ISSUE THREAD

**Issue by alexandru** [raboof/sbt-reproducible-builds#163]
Hey,

Trying to use this plugin, and unfortunately I've bumped into an issue — [see build](https://github.com/monix/monix/runs/968452305?check_suite_focus=true):

```
[error] java.lang.UnsupportedOperationException: empty.max
[error] 	at scala.collection.TraversableOnce.max(TraversableOnce.scala:234)
[error] 	at scala.collection.TraversableOnce.max$(TraversableOnce.scala:232)
[error] 	at scala.collection.AbstractTraversable.max(Traversable.scala:108)
[error] 	at net.bzzt.reproduciblebuilds.Certification$.apply(Certification.scala:118)
[error] 	at net.bzzt.reproduciblebuilds.ReproducibleBuildsPlugin$.$anonfun$ourCertification$1(ReproducibleBuildsPlugin.scala:61)
[error] 	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
[error] 	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
[error] 	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
[error] 	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
[error] 	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
[error] 	at sbt.Execute.work(Execute.scala:290)
[error] 	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
[error] 	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error] 	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[error] 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[error] 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[error] 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[error] 	at java.lang.Thread.run(Thread.java:748)
[error] (packagedArtifacts) java.lang.UnsupportedOperationException: empty.max
[error] Total time: 84 s (01:24), completed Aug 10, 2020 8:37:49 PM
##[error]Process completed with exit code 1.
```

Any ideas?

Thanks,

**Comment by raboof** [comment]
Hmm, this looks like it was triggered by running the reproducible builds plugin on a (sub)project that has no artifacts.

The workaround is probably to disable the plugin for that (sub)project.

The fix would probably be to not add a certification to (sub)projects without artifacts - after all, there's nothing to certify, right?

**Comment by alexandru** [comment]
Yes, that's what I did, seems to be working.

**Comment by alexandru** [comment]
Error message is confusing. As a suggestion, maybe trigger an exception that suggests a fix.

Very useful plugin btw, thanks.

**Comment by raboof** [comment]
> Error message is confusing. As a suggestion, maybe trigger an exception that suggests a fix.

Yeah that's definitely an oversight - suggesting a fix in the exception would be a useful first step, but just handling this situation in the plugin in the first place would be good too :)
